### ISSUE TITLE
[frontend] [native] Meta information

### ISSUE THREAD

**Issue by MaxwellBo** [MaxwellBo/kingfisher-frontend#9]
A lot of our meta information is currently placeholder data:

- [x] `favicon.ico` (currently [this](https://github.com/MaxwellBo/kingfisher-frontend/blob/dev/public/favicon.ico))
- [x] `favicon.ico` (currently [this](https://github.com/MaxwellBo/kingfisher-frontend/blob/dev/public/manifest.json))
- [x] `<title>` (currently [this](https://github.com/MaxwellBo/kingfisher-frontend/blob/dev/public/index.html#L23))
- [ ] App logos for iOS and Android
- [x] More extensive meta information for `[frontend]` (including bookmark logos at various sizes, search engine result summaries, etc.)
   + [ ] Ask Charlie Groves how he generated these for `SyncUQ`
